insert into patologias (nome, ativo, descricao) values ('Arroyo Willow', false, 'Lap bi indir ing hrn-grf');
insert into patologias (nome, ativo, descricao) values ('Sensitive Tooth Paste', true, 'Simple suture of dura');
insert into patologias (nome, ativo, descricao) values ('HOUSE DUST', false, 'Drain appendiceal absc');
insert into patologias (nome, ativo, descricao) values ('Smart Sense Childrens Multi Symptom Cold Relief', false, 'Closed aortic valvotomy');
insert into patologias (nome, ativo, descricao) values ('PHYTOGENIC INFINITE POWDER FOUNDATION', true, 'Wrist structure division');
insert into patologias (nome, ativo, descricao) values ('AMLODIPINE BESYLATE', true, 'Reopen laminectomy site');
insert into patologias (nome, ativo, descricao) values ('Temazepam', true, 'Remove impl device NEC');
insert into patologias (nome, ativo, descricao) values ('Oxytocin', true, 'Adrenal reimplantation');
insert into patologias (nome, ativo, descricao) values ('Berry Scented Hand Sanitizer', true, 'Release of chordee');
insert into patologias (nome, ativo, descricao) values ('Sertraline Hydrochloride', true, 'Open sigmoidectomy NEC');
insert into patologias (nome, ativo, descricao) values ('Oxygen', false, 'Obstetric operation NEC');
insert into patologias (nome, ativo, descricao) values ('Pure Finish Mineral Powder Foundation SPF 20', false, 'Atmos press/compos contr');
insert into patologias (nome, ativo, descricao) values ('Luminous Intensive Decollote Treatment SPF 20', false, 'Cervical biopsy NEC');
insert into patologias (nome, ativo, descricao) values ('Haloperidol', false, 'Open sigmoidectomy NEC');
insert into patologias (nome, ativo, descricao) values ('Glipizide', true, 'Labial frenotomy');
insert into patologias (nome, ativo, descricao) values ('Carbidopa and Levodopa', true, 'Closed intra-abd mass bx');
insert into patologias (nome, ativo, descricao) values ('Vida Mia Hand Sanitizer', false, 'C & s-eye');
insert into patologias (nome, ativo, descricao) values ('Appetite Increase', false, 'Laparoscopy');
insert into patologias (nome, ativo, descricao) values ('Equate Hemorrhoidal Medicated Wipes', false, 'Unilat reduct mammoplast');
insert into patologias (nome, ativo, descricao) values ('Pain Relief Anti inflammatory', true, 'Vaginal const w grf/pros');
insert into patologias (nome, ativo, descricao) values ('all day relief', true, 'C-luc exc max sinus les');
insert into patologias (nome, ativo, descricao) values ('Olanzapine', false, 'Pineal operation NEC');
insert into patologias (nome, ativo, descricao) values ('ADVANCED TIME ZONE AGE REVERSING', false, 'Other bone dx proc NOS');
insert into patologias (nome, ativo, descricao) values ('Olanzapine', false, 'Op red-radius/uln epiphy');
insert into patologias (nome, ativo, descricao) values ('ESIKA Extreme Moisturizing SPF 16', true, 'Perianal excision NEC');
insert into patologias (nome, ativo, descricao) values ('Glyburide and Metformin Hydrochloride', true, 'Mumps vaccination');
insert into patologias (nome, ativo, descricao) values ('Cold Relief', false, 'Head scan NEC');
insert into patologias (nome, ativo, descricao) values ('PediaCare Childrens Cough and Congestion', false, 'Rad dissec thorac struct');
insert into patologias (nome, ativo, descricao) values ('GOJO Antibacterial', true, 'Open bronchial biopsy');
insert into patologias (nome, ativo, descricao) values ('PURE RED GINSENG', true, 'Anal anastomosis');
insert into patologias (nome, ativo, descricao) values ('CLE DE PEAU BEAUTE RADIANT FLUID FOUNDATION', false, 'Manual explor uterus p/p');
insert into patologias (nome, ativo, descricao) values ('Nifedipine', false, 'Trnsapcl rep aortc valve');
insert into patologias (nome, ativo, descricao) values ('Methylphenidate Hydrochloride', false, 'Closed mitral valvotomy');
insert into patologias (nome, ativo, descricao) values ('smart sense nighttime', false, 'Patellar biopsy');
insert into patologias (nome, ativo, descricao) values ('Tolterodine Tartrate', true, 'Arterial puncture NEC');
insert into patologias (nome, ativo, descricao) values ('Gas Relief', false, 'Ins spin disc pros thor');
insert into patologias (nome, ativo, descricao) values ('CLARINS HydraQuench Tinted Moisturizer Broad Spectrum SPF 6 01 NATUREL', true, 'Opn fx red w int fix NEC');
insert into patologias (nome, ativo, descricao) values ('Levofloxacin', true, 'LITT lesn liver,guidance');
insert into patologias (nome, ativo, descricao) values ('Dark Foundation SPF 15', false, 'Periph nerv anastom NEC');
insert into patologias (nome, ativo, descricao) values ('ACYCLOVIR', false, 'Osteoclasis-metatar/tar');
insert into patologias (nome, ativo, descricao) values ('HydrALAZINE Hydrochloride', true, 'IVUS peripheral vessels');
insert into patologias (nome, ativo, descricao) values ('Pramipexole dihydrochloride', false, 'Intravas img cor ves OCT');
insert into patologias (nome, ativo, descricao) values ('Atenolol', false, 'Tu remov ureter obstruct');
insert into patologias (nome, ativo, descricao) values ('Sodium Chloride', false, 'Periph nerve inject NEC');
insert into patologias (nome, ativo, descricao) values ('Famotidine', false, 'Pancreatic homotransplan');
insert into patologias (nome, ativo, descricao) values ('Green Pea', true, 'Parasitology-nerv syst');
insert into patologias (nome, ativo, descricao) values ('DIVALPROEX SODIUM', true, 'Revis bile tract anastom');
insert into patologias (nome, ativo, descricao) values ('Baclofen', true, 'Lumb/lmbsac fus ant/post');
insert into patologias (nome, ativo, descricao) values ('Primidone', false, 'Rem crtd sinus stm, totl');
insert into patologias (nome, ativo, descricao) values ('Shagbark Hickory', false, 'Cord bld stem cell trans');
