insert into especie (especieid, descricao) values (1, 'Jackal, asiatic');
insert into especie (especieid, descricao) values (2, 'Black-crowned crane');
insert into especie (especieid, descricao) values (3, 'Waxbill, violet-eared');
insert into especie (especieid, descricao) values (4, 'Cape cobra');
insert into especie (especieid, descricao) values (5, 'Puma');
insert into especie (especieid, descricao) values (6, 'White-headed vulture');
insert into especie (especieid, descricao) values (7, 'Gonolek, burchell''s');
insert into especie (especieid, descricao) values (8, 'Grouse, sage');
insert into especie (especieid, descricao) values (9, 'Egyptian vulture');
insert into especie (especieid, descricao) values (10, 'Common dolphin');
insert into especie (especieid, descricao) values (11, 'Legaan, ground');
insert into especie (especieid, descricao) values (12, 'Trumpeter, green-winged');
insert into especie (especieid, descricao) values (13, 'Ring-tailed gecko');
insert into especie (especieid, descricao) values (14, 'Otter, cape clawless');
insert into especie (especieid, descricao) values (15, 'Gecko, barking');
insert into especie (especieid, descricao) values (16, 'Grebe, little');
insert into especie (especieid, descricao) values (17, 'Roseate cockatoo');
insert into especie (especieid, descricao) values (18, 'Gaur');
insert into especie (especieid, descricao) values (19, 'Columbian rainbow boa');
insert into especie (especieid, descricao) values (20, 'Weaver, white-browed sparrow');
insert into especie (especieid, descricao) values (21, 'Gelada baboon');
insert into especie (especieid, descricao) values (22, 'Cormorant, little');
insert into especie (especieid, descricao) values (23, 'Eurasian badger');
insert into especie (especieid, descricao) values (24, 'Comb duck');
insert into especie (especieid, descricao) values (25, 'Bat, little brown');
insert into especie (especieid, descricao) values (26, 'Dragon, western bearded');
insert into especie (especieid, descricao) values (27, 'Badger, honey');
insert into especie (especieid, descricao) values (28, 'Red hartebeest');
insert into especie (especieid, descricao) values (29, 'Partridge, coqui');
insert into especie (especieid, descricao) values (30, 'Rat, arboral spiny');
insert into especie (especieid, descricao) values (31, 'Gecko, ring-tailed');
insert into especie (especieid, descricao) values (32, 'Greater roadrunner');
insert into especie (especieid, descricao) values (33, 'Turkey vulture');
insert into especie (especieid, descricao) values (34, 'Three-banded plover');
insert into especie (especieid, descricao) values (35, 'Mule deer');
insert into especie (especieid, descricao) values (36, 'Gull, silver');
insert into especie (especieid, descricao) values (37, 'White-lipped peccary');
insert into especie (especieid, descricao) values (38, 'Legaan, water');
insert into especie (especieid, descricao) values (39, 'Common duiker');
insert into especie (especieid, descricao) values (40, 'South American puma');
insert into especie (especieid, descricao) values (41, 'Pied cormorant');
insert into especie (especieid, descricao) values (42, 'Dama wallaby');
insert into especie (especieid, descricao) values (43, 'Pintail, white-cheeked');
insert into especie (especieid, descricao) values (44, 'Marabou stork');
insert into especie (especieid, descricao) values (45, 'Cat, european wild');
insert into especie (especieid, descricao) values (46, 'Cobra, egyptian');
insert into especie (especieid, descricao) values (47, 'Kangaroo, red');
insert into especie (especieid, descricao) values (48, 'Bengal vulture');
insert into especie (especieid, descricao) values (49, 'Cat, toddy');
insert into especie (especieid, descricao) values (50, 'Spotted hyena');
